# --------------------|
# -----03/07/2023-----|
# (C) Mukanov Murager |
# --------------------|

name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Chekcout repository
        uses: actions/checkout@v3
      
      - name: Building
        run: docker build -t vue-app .

# Need to define approach of deploying contaier to Github Pages
